# Task 1

In [3]:
import numpy as np

array_1d = np.random.randint(1, 100, 10)
array_1d

array([83,  6, 38, 90, 11, 43, 12, 41, 15, 96])

In [6]:
print(array_1d[0])

83


In [7]:
print(array_1d[-1])

96


In [11]:
array_2d = np.random.rand(3, 3)

array_2d

array([[0.11623904, 0.04504768, 0.77989936],
       [0.02554874, 0.01468987, 0.43364362],
       [0.01659211, 0.96904534, 0.07170672]])

# Task 2

In [12]:
print(array_2d[0])

[0.11623904 0.04504768 0.77989936]


In [23]:
print(array_2d[:,2])

[0.77989936 0.43364362 0.07170672]


In [47]:
new_array = array_2d[0:2, 0:2]

new_array

array([[0.11623904, 0.04504768],
       [0.02554874, 0.01468987]])

# Task 3

In [42]:
array1 = np.random.randint(0,100,5)
array2 = np.random.randint(0,100,5)

print("Array 1")
print(array1)
print("\nArray 2")
print(array2)

Array 1
[81 69 63 43 72]

Array 2
[99 94 66  1 23]


In [43]:
print(array1 + array2)

[180 163 129  44  95]


In [44]:
print(array1 * array2)

[8019 6486 4158   43 1656]


In [46]:
print(array1 ** 2)

[6561 4761 3969 1849 5184]


# Task 4

In [49]:
array_A = np.random.randint(0, 100, (2,3))

array_B = np.random.randint(0, 100, (3,2))

print("Array A")
print(array_A)
print("\nArray B")
print(array_B)

Array A
[[46  1 80]
 [49 28 61]]

Array B
[[21 26]
 [53 29]
 [55 39]]


In [50]:
matrix_mult_result = array_A @ array_B

print(matrix_mult_result)

[[5419 4345]
 [5868 4465]]


In [51]:
element_wise_mult = array_A * array_B

print(element_wise_mult)

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

Does not work because the two arrays have different shapes. 